### ISSUE TITLE
API-KEY

### ISSUE THREAD

**Issue by senimamsistem** [downygg/GameeMining#4]
api key ambil dimana bang

**Comment by downygg** [comment]
re-check readme

**Comment by senimamsistem** [comment]
cek bang

TX: 5nG59o8cmViWokJhNhRKD8Dwcw1hafLbXthFh6gALdED

**Comment by senimamsistem** [comment]
Done send bang but API-KEY email name still Invalid 

![WhatsApp Image 2024-06-05 at 17 02 49_a3f9e3ef](https://github.com/downygg/GameeMining/assets/42347017/343ca37c-c00f-4dc8-b126-aa4446460a5a)

**Comment by downygg** [comment]
approved. Try again

Pada Rab, 5 Jun 2024 pukul 16.04 senimam | sistem ***@***.***>
menulis:
