### ISSUE TITLE
Check Form Please - i already donate

### ISSUE THREAD

**Issue by jamaluunn** [downygg/GameeMining#5]

**Comment by downygg** [comment]
approved

Pada Rab, 5 Jun 2024 pukul 14.24 Keenz ***@***.***> menulis:

**Comment by baztardengine** [comment]
bro please check ranwaysis@gmail.com already donate 0.2 sui 
GCEGFBf8ZJ11K2xN4tmVw2fQfcK13CY9AUawbfrtSUTL

**Comment by downygg** [comment]
Send with new email. Your api key was leaked

Pada Rabu, 05 Juni 2024, baztardengine ***@***.***> menulis:

**Comment by baztardengine** [comment]
wait

**Comment by baztardengine** [comment]
please approve bro D1YfzDMCw9K3ud58UCK6QaLcMW3Gwy5W87qWYBt757HV

**Comment by downygg** [comment]
approved

Pada Rab, 5 Jun 2024 pukul 21.39 baztardengine ***@***.***>
menulis:
